#!/bin/bash

render.py /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}/config/server.properties.jinja2 > /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}/config/server.properties
echo "Config: "
cat /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}/config/server.properties
exec  /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}/bin/kafka-server-start.sh  /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}/config/server.properties
